version: "3.8"

services:
  frontend:
    build:
      context: ../web
    ports:
      - "3000:3000"
    volumes:
      - ../web/src:/app/src
      - /app/node_modules
    networks:
      - public
    depends_on:
      - backend

  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    command: npm run start
    environment:
      - DATABASE_DB=blog_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=blog-db
      - NODE_ENV=development
    secrets:
      - db-password
    volumes:
      - ./src:/app/src
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
    depends_on:
      - blog-db

  blog-db:
    image: mysql@sha256:04ee7141256e83797ea4a84a4d31b1f1bc10111c8d1bc1879d52729ccd19e20a
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
#    secrets:
#      - db-password
    env_file:
      - ./src/db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=blog_db
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: ./src/db-password.txt
