version: "3.8"

services:
  frontend:
    build:
      context: ../web
    ports:
      - "3000:3000"
    volumes:
      - ../web/src:/app/src
      - /app/node_modules
    networks:
      - public
    depends_on:
      - backend

  backend:
    build:
      context: ./
    ports:
      - "8001:8001"
    command: npm run start
    environment:
      - DATABASE_DB=blog_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    secrets:
      - db-password
    networks:
      - public
      - private
    depends_on:
      - blog-db

  blog-db:
    image: mysql@sha256:04ee7141256e83797ea4a84a4d31b1f1bc10111c8d1bc1879d52729ccd19e20a
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=blog_db
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

#  blog-redis:
#    image: redis:@sha256:08e282682a708eb7f51b473516be222fff0251cdee5ef8f99f4441a795c335b6

networks:
  public:
  private:
volumes:
  back-notused:
  db-data:
secrets:
  db-password:
    file: ./db-password.txt
