AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with cfn-response.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: arn:aws:iam::160071257600:role/service-role/rabit-cli-function-role-c60nm0au
      Handler: index.handler
      Code:
        ZipFile: |
          var aws = require('aws-sdk')
          var response = require('cfn-response')
          exports.handler = function(event, context) {
              console.log("ENVIRONMENT VARIABLES\n" + JSON.stringify(process.env, null, 2))
              console.log("EVENT\n" + JSON.stringify(event, null, 2))
          return context.logStreamName
          }
      Description: deploy lambda function.
      TracingConfig:
        Mode: Active